language: java
install: true
script:
  - bash build.sh
env:
  global:
  - secure: g0A9usPhe/Tj0lnuCwUHgA88fsJ0eU1sgBCUUEUXDSE9wqyHs8ossEagRXOv3RFA+mULCXHuiSyD0CCkvfSfvL9zYzZO3XOcNiMy8GWZahUtYJph256bvw8D5/Y+HJTD8ppvPYjptKs6RyQSfQw796XIMUWHQQhUaKX6a2jho40=
  - secure: aV7iNqT38xPCa0PaDP9daA0ykB08j6tK+hVp5aEiQLmZZqCZXnSzPNESZDvLq7IqT5vbynNGMti96gi0jVEnltFY+5ZTSXEmSQycYNzoBOG2zRrb3mk5rYBd3cu/vvA8J3JvJEb+oRuIt8rCL27Qa/oL/+qdvL+vlPnHPK0v+zo=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cRwkspFGljS0CPHGsYmpKCP9tSDdGRNv40zJa8+GL6rsiMeAGnbOuVNkkGMFK6whXh5Xwc6dgX2a5s04Qo2Uivvu3qANLlTccRsthnufJM0RG9B+atZhbqgNF6Njpuy6O4afdGdcMsceBErLhgK8f18VVKUyFZ5NTbDnornD5QQ=
  file: target/*.jar
  file_glob: true
  on:
    tags: true
    repo: AlienVault-OTX/OTX-Java-SDK
